### ISSUE TITLE
Insert Mapa e Objetivos.

### ISSUE THREAD

**Issue by JoaoHenrique12** [SBD1/Grupo02-MetalGearSolid#11]
Crie o mapa com os respectivos terrenos, posicione os objetivos primarios e secundarios no mapa. Seria bom que houvesse pelo menos um mapa dentro do outro.

- [x] Insert Mapas, pelo menos um mapa dentro do outro.
- [x] Insert de Objetivos.
- [x] Posicionar Objetivos nos mapas.

**Comment by RafaelBP02** [comment]
Esqueci de colocar o codigo dessa issue nesse comit: https://github.com/SBD1/Grupo02-MetalGearSolid/commit/9c7d328af2895108d80b9d4590808c92f9b52969
