### ISSUE TITLE
Insert Codinome

### ISSUE THREAD

**Issue by JoaoHenrique12** [SBD1/Grupo02-MetalGearSolid#14]
- [x] Inserir os codinomes de acordo com o site: [LINK](https://metalgear.fandom.com/wiki/Codename_(gameplay)#Metal_Gear_Solid_V:_The_Phantom_Pain), se possivel traduzir para PT-BR.

**Comment by RafaelBP02** [comment]
Foram inseridos 5 codinomes na branch sql
