### ISSUE TITLE
NPC, Uniforme, Item, Arma.

### ISSUE THREAD

**Issue by JoaoHenrique12** [SBD1/Grupo02-MetalGearSolid#16]
- [x] Insert 20 NPCs
- [x] Equipar NPCs com uniformes ja adicionados.
- [x] Insert Itens
- [x] Equipar itens em NPC
- [x] Insert Armas
- [x] Equipar armas em NPC

**Comment by lucasqueiroz23** [comment]
Adicionamos algumas armas no arquivo Armas.sql. Precisamos adicionar mais armas depois.

**Comment by lucasqueiroz23** [comment]
Inseri 20 NPCs. Falta adicionar as FKs e PKs e alterar os níveis.
