### ISSUE TITLE
Ajustes do projeto

### ISSUE THREAD

**Issue by JoaoHenrique12** [SBD1/Grupo02-MetalGearSolid#25]
- [x] Tabela REQUISITO some.
    - [x]  PROJETO se relaciona diretamente com UNIDADE.
    - [x]   O relacionamento ProjetoDepenteUnidade fica com o atributo tipo e o relacionamento passa a ter cardinalidade 1:10.
    - [x]  PROJETO se relaciona diretamente com RECURSO.
    - [x]   O relacionamento ProjetoConsomeRecurso fica com o atributo tipo e o relacionamento passa a ter cardinalidade 1:14.
- [x] Adicionar no DDL o valor default de PROJETO depende UNIDADE e PROJETO consome RECURSO para 0, seja para requisito de USO ou PRODUCAO.
- [x] Os atributos com nome TIPO precisam ser descritos no MER, faça um texto falando quais valores eles podem assumir.

Nota: Todas as alterações do MER e DLD tem que ser propagadas para o arquivo de criação do banco (DDL e DML).

**Comment by RafaelBP02** [comment]
O professor também tinha recomendado fazer a especialização das armas

**Comment by RafaelBP02** [comment]
Sobre a sujestão: "O relacionamento ProjetoDepenteUnidade fica com o atributo tipo e o relacionamento passa a ter cardinalidade 1:10". Não vejp sentido nessa cardinalidade. Porque assim eu entendo que uma unidade só poderá ser requisito de no máximo 10 projetos.

**Comment by JoaoHenrique12** [comment]
A questão é que o projeto pode depender de no máximo 5 unidades. Pensando no que vc comentou agora acho que a cardinalidade pode permanecer a mesma, já que com esta alteração uma mesma tupla poderia ter como requisito 10 unidades e não 5. Assim sendo, mantenha as cardinalidades dos recursos e unidades.

**Comment by RafaelBP02** [comment]
Sobre a sujestão: "Adicionar no DDL o valor default de PROJETO depende UNIDADE e PROJETO consome RECURSO para 0, seja para requisito de USO ou PRODUCAO". Não entendi qual atributo deve ter default = 0. Pois a tabela de requisitos não existe mais.

**Comment by JoaoHenrique12** [comment]
Em PROJETO depende requisito existe o atributo nivelUnidade, coloca o default dele como 0 e faz o mesmo para Projeto consome Recurso, coloca a quantidade com default 0.

**Comment by JoaoHenrique12** [comment]
> O professor também tinha recomendado fazer a especialização das armas

#32 , vamos especializar o Item. Acho que fica mais facil.
