### ISSUE TITLE
Especialização de ITEM.

### ISSUE THREAD

**Issue by JoaoHenrique12** [SBD1/Grupo02-MetalGearSolid#32]
Item fica com nome, descricao, idItem, tipo (enum que pode assumir 'CONSUMIVEL', 'DANO').
No MREL a FK de item passa para DANO ou para CONSUMIVEL.

- [x] Tabela 1   DANO:  probNocaute, dano. 
- [x] Tabela 2   CONSUMIVEL: taxaAumentoDanoArma, taxaAumentoCamuflagem, taxaAumentoDefesa.   
- [x] Lembrem de colocar uma restricao para que os valores que atributos que envolvem probabilidades estejam no intervalo [1,100].

Ao alterar o DDL, lembre-se de inserir novos itens.

PS: O nome do Item fica com 2 sublinhados e nao 1, no MER.

**Comment by JoaoHenrique12** [comment]
Aproveitando que vcs vao mexer no MER, MREL e DDL. Altera o nome quantidade no relacionamento Projeto Consome Recurso para qtdProcessado. Fica mais coerente com a proposicao do jogo.

**Comment by RafaelBP02** [comment]
taxaAumentoDanoArma, taxaAumentoCamuflagem, taxaAumentoDefesa é razoavel variarem de 0 a 100. Pois nem todos os itens são obrigados a possuir todas essas taxas
