### ISSUE TITLE
MER e DLD

### ISSUE THREAD

**Issue by JoaoHenrique12** [SBD1/Grupo02-MetalGearSolid#4]
Para cumprir esta issue devem ser feitas as seguintes atividades:
- [x] Verificar se a cardinalidade está invertida no MER, se sim corrigi-lá
- [x] Alterar o atributo "nome" da tabela missão para "titulo".
- [x] Alterar no DLD o atributo "descrição" da tabela missão para que ela aceite até 2000 caracteres.
- [x] Adicionar na tabela estatística atributos: codinome #6 e rank.
- [x] O nome de cada player deve ser único, se houver necessidade de adicionar esta informação em algum diagrama faça.
- [x] Verificar se as especializações podem ser omitidas, como está atualmente no MER, ou se elas precisam ser expressas de maneira explicita. Caso precisem ser expressas outra issue será criada.

**Comment by lucasqueiroz23** [comment]
Oi, pessoal. Dei uma alterada no MER pra corrigir a cardinalidade. Falta revisar e alterar, também, o MREL.
